vich_uploader:
    db_driver: orm
    metadata:
        type : attribute

    mappings:
        property:
            uri_prefix: /images/property
            upload_destination: '%kernel.project_dir%/public/images/items'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: false
